version: '3'
services:
  app:
    build:
      context: .
# =========ローカルと本番切り替え===========
    #command: bundle exec puma -C config/puma.rb -e production
    command: bundle exec puma -C config/puma.rb
# ======================================

    volumes:
      - .:/portfolio
      - public-data:/portfolio/public
      - tmp-data:/portfolio/tmp
      - log-data:/portfolio/log
    ports:
      - 3000:3000  
    networks:
      - portfolio-network
# =========ローカルと本番切り替え===========     
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: portfolio_development
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 33306:3306
    networks:
      - portfolio-network
# =========ローカルと本番切り替え===========     

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/portfolio/public
      - tmp-data:/portfolio/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - portfolio-network  

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  portfolio-network:
    external: true
